# Generated by Django 4.2.4 on 2023-08-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(2, 'MALE'), (3, 'FEMALE'), (5, 'NONBINARY')])),
                ('orientation', models.IntegerField(choices=[(2, 'M'), (3, 'F'), (5, 'NB'), (6, 'MF'), (10, 'MNB'), (15, 'FNB'), (30, 'MFNB')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Enduser',
        ),
    ]
