# Generated by Django 4.2.4 on 2023-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yentas', '0002_client_delete_enduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='USA', max_length=200, primary_key=True, serialize=False),
        ),
    ]
